DotNet/Chloe.Home/Models/WikiMenuTreeNode.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Chloe.Home.Models
{
    public class WikiMenuTreeNode
    {
        public WikiMenuTreeNode()
        {
            this.ChildNodes = new List<WikiMenuTreeNode>();
        }
        public string Id { get; set; }
        public string ParentId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string DocumentId { get; set; }
        //public bool Expanded { get; set; }
        //public bool Expanded { get; set; }
        public List<WikiMenuTreeNode> ChildNodes { get; set; }
    }
}

DotNet/Chloe.Home/Controllers/HomeController.cs
using Chloe.Application.Interfaces;
using Chloe.Application.Interfaces.Wiki;
using Chloe.Application.Models.WikiDocument;
using Chloe.Home.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chloe.Home.Controllers
{
    public class HomeController : WebController
    {
        // GET: Home
        [OutputCache(Duration = WebConsts.PageOutputCacheDuration)]
        public ActionResult Index()
        {
            return View();
        }

        [OutputCache(Duration = WebConsts.PageOutputCacheDuration, VaryByParam = "id")]
        public ActionResult UpgradeNotes(string id)
        {
            string docId = id;

            WikiDocumentDetailModel model = this.CreateService<IWikiDocumentAppService>().GetDetailModel(docId);

            if (model == null)
            {
                /* 404 */
                return this.NotFound();
            }

            this.ViewBag.Document = model;
            return View();
        }
    }
}

DotNet/Chloe.Home/Controllers/WikiController.cs
using Chloe.Application.Interfaces;
using Chloe.Application.Interfaces.Wiki;
using Chloe.Application.Models.WikiDocument;
using Chloe.Entities;
using Chloe.Home.Common;
using Chloe.Home.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Chloe.Home.Controllers
{
    public class WikiController : WebController
    {
        [OutputCache(Duration = WebConsts.PageOutputCacheDuration, VaryByParam = "id")]
        public ActionResult Document(string id)
        {
            List<WikiMenuItem> menuItems = this.CreateService<IWikiMenuItemAppService>().GetWikiMenuItems();
            List<WikiMenuTreeNode> rootNodes = this.CreateTreeNodes(menuItems);

            this.ViewBag.RootNodes = rootNodes;

            string docId = id ?? rootNodes.First().ChildNodes.First().DocumentId;

            WikiDocumentDetailModel model = this.CreateService<IWikiDocumentAppService>().GetDetailModel(docId);

            if (model == null)
            {
                /* 404 */
                return this.NotFound();
            }

            this.ViewBag.Document = model;

            WikiMenuItem menuItem = menuItems.Where(a => a.DocumentId == model.Id).FirstOrDefault();

            if (menuItem != null)
            {
                string expandedNodeId = menuItem.Id;
                this.ViewBag.CurrentNodeId = expandedNodeId;
            }

            return View();
        }

        List<WikiMenuTreeNode> CreateTreeNodes(List<WikiMenuItem> menuItems)
        {
            List<WikiMenuItem> rootItems = menuItems.Where(a => a.ParentId == null).OrderBy(a => a.SortCode).ToList();

            List<WikiMenuTreeNode> rootNodes = new List<WikiMenuTreeNode>(rootItems.Count);
            foreach (var item in rootItems)
            {
                WikiMenuTreeNode rootNode = new WikiMenuTreeNode();
                rootNode.Id = item.Id;
                rootNode.Name = item.Name;

                foreach (WikiMenuItem childItem in menuItems.Where(a => a.ParentId == rootNode.Id).OrderBy(a => a.SortCode))
                {
                    WikiMenuTreeNode childNode = new WikiMenuTreeNode() { Id = childItem.Id, ParentId = childItem.ParentId, Name = childItem.Name, DocumentId = childItem.DocumentId };

                    RouteValueDictionary parameDic = new RouteValueDictionary();
                    parameDic.Add("id", childItem.DocumentId);
                    string url = this.Url.Action("Document", parameDic);
                    childNode.Url = url;

                    rootNode.ChildNodes.Add(childNode);
                }

                rootNodes.Add(rootNode);
            }

            return rootNodes;
        }
    }
}

DotNet/Chloe.Home/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Chloe's home";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

@section ScriptAndStyle{
    @ContentHelper.RefStyle("~/Content/css/animate.min.css")
    @ContentHelper.RefStyle("~/Content/css/vegas.min.css")
    @ContentHelper.RefStyle("~/Content/css/index.css")

    @ContentHelper.RefScript("~/Content/js/vegas.min.js")
    @ContentHelper.RefScript("~/Content/js/wow.min.js")
    @ContentHelper.RefScript("~/Content/js/index.js")
}

<section class="preloader">
    <div class="sk-circle">
        <div class="sk-circle1 sk-child"></div>
        <div class="sk-circle2 sk-child"></div>
        <div class="sk-circle3 sk-child"></div>
        <div class="sk-circle4 sk-child"></div>
        <div class="sk-circle5 sk-child"></div>
        <div class="sk-circle6 sk-child"></div>
        <div class="sk-circle7 sk-child"></div>
        <div class="sk-circle8 sk-child"></div>
        <div class="sk-circle9 sk-child"></div>
        <div class="sk-circle10 sk-child"></div>
        <div class="sk-circle11 sk-child"></div>
        <div class="sk-circle12 sk-child"></div>
    </div>
</section>
<div id="slide-images" style="display:none;">
    <span>@Url.Content("~/Content/images/slide-1.jpg")</span>
    <span>@Url.Content("~/Content/images/slide-2.jpg")</span>
</div>

<!-- home section -->
<section id="home">
    <div class="container">
        <div class="row">

            <div class="col-md-offset-2 col-md-8 col-sm-12">
                <div class="home-thumb">
                    <h3 class="wow fadeInUp" data-wow-delay="0.4s">Hello,I am chloe</h3>
                    <h1 class="wow fadeInUp" data-wow-delay="0.6s">WELCOME TO MY HOME</h1>
                    <!--<h3 class="wow fadeInUp" data-wow-delay="0.6s">We are almost <strong>ready to launch</strong> our <strong>new creative</strong> website!</h3>-->
                    <a href="@this.Url.Action("Document", "Wiki")" class="btn btn-lg btn-default smoothScroll wow fadeInUp hidden-xs" data-wow-delay="0.8s">Let's begin</a>
                    <!--<a href="#" data-toggle="modal" data-target="#modal1" class="btn btn-lg btn-success smoothScroll wow fadeInUp" data-wow-delay="1.0s">Notify me!</a>-->
                </div>
                <br />
                <div>
                    <iframe id="github-star" style="border:none;" width="105" height="20"></iframe>
                    <iframe id="github-fork" style="border:none;" width="105" height="20"></iframe>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- about section -->
<section id="about">
    <div class="container">
        <div class="row">

            <div class="col-md-6 col-sm-12">
                <img src="@Url.Content("~/Content/images/ORMicon(330x330).png")" class="img-responsive wow fadeInUp" alt="About">
            </div>

            <div class="col-md-6 col-sm-12">
                <div class="about-thumb">
                    <div class="section-title">
                        <h1 class="wow fadeIn" data-wow-delay="0.2s">About me</h1>
                    </div>
                    <div class="wow fadeInUp" data-wow-delay="0.6s">
                        <p>I am a lightweight and high-performance Object/Relational Mapping(ORM) library for .NET --C#.</p>
                        <p>My query interface is similar to LINQ.You can query data like LINQ and do any things(Join Query | Group Query | Aggregate Query | Insert | Batch Update | Batch Delete) by lambda with me.</p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

<!-- feature section -->
<section id="feature">
    <div class="container">
        <div class="row">

            <svg preserveAspectRatio="none" viewBox="0 0 100 102" height="100" width="100%" version="1.1" xmlns="http://www.w3.org/2000/svg" class="svgcolor-light">
                <path d="M0 0 L50 100 L100 0 Z"></path>
            </svg>

            <div class="col-md-4 col-sm-6">
                <div class="media wow fadeInUp" data-wow-delay="0.4s">
                    <div class="media-object media-left">
                        <i class="icon icon-laptop"></i>
                    </div>
                    <div class="media-body">
                        <h2 class="media-heading">纯对象化</h2>
                        <p>增删查改都是基于 lambda 表达式树，全对象化编程，智能提示，编译检查，容错率极高</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4 col-sm-6">
                <div class="media wow fadeInUp" data-wow-delay="0.8s">
                    <div class="media-object media-left">
                        <i class="icon icon-refresh"></i>
                    </div>
                    <div class="media-body">
                        <h2 class="media-heading">高性能</h2>
                        <p>轻量即高效，框架注重数据库访问，没有重度封装与设计，整个框架体积不足200KB。DataReader 向实体转换使用了 Emit 生成 il 代码的方式，避免反射带来大量计算损耗，实体映射速度比肩 Dapper，接近手写</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4 col-sm-8">
                <div class="media wow fadeInUp" data-wow-delay="1.2s">
                    <div class="media-object media-left">
                        <i class="icon icon-chat"></i>
                    </div>
                    <div class="media-body">
                        <h2 class="media-heading">多数据库</h2>
                        <p>支持 SqlServer、MySql、Sqlite 以及 Oracle 等主流数据库，灵活切换数据库，亦可在一个项目中同时使用多种数据库</p>
                    </div>
                </div>
            </div>

            <div class="clearfix text-center col-md-12 col-sm-12">
                <a href="@this.Url.Action("Document", "Wiki")" class="btn btn-default smoothScroll">Getting start</a>
            </div>

        </div>
    </div>
</section>

DotNet/Chloe.Home/Views/Home/UpgradeNotes.cshtml
@{
    WikiDocumentDetailModel doc = this.ViewBag.Document;
    ViewBag.Title = doc.Title;
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
@using Chloe.Application.Models.WikiDocument;
@section ScriptAndStyle{
    @Html.RefStyle("~/Content/editormd/css/editormd.min.css")
    @Html.RefScript("~/Content/editormd/lib/prettify.min.js")
}
<script>
    $(function () {
        $(".bodyContent pre").addClass("prettyprint");/* linenums */
        PR.prettyPrint();
    });
</script>
<div style="margin-top:100px;width:800px;min-height:750px; margin-left: auto;margin-right: auto;border: 1px solid #d3d3d3;" class="mainwrapper" id="upgrade-notes">
    <div id="content">
        <div id="bodyContent" class="bodyContent markdown-body editormd-preview-container">
            @Html.Raw(doc.HtmlContent)
        </div>
    </div>
</div>

DotNet/Chloe.Home/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "亲，别迷路了哦~";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div style="margin:auto;width:400px;margin-top:200px;min-height:650px;">
    <img src="@Url.Content("~/Content/images/zero.jpg")" /><span style="font-family:'Microsoft YaHei'"> 亲，别迷路了哦~</span>
</div>

DotNet/Chloe.Home/Views/Shared/_LayoutPage.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta name="keywords" content="Chloe,ORM,.NET,Core,C#,数据库访问,性能高,高性能,好用">
    <meta name="description" content="A lightweight and high-performance Object/Relational Mapping(ORM) library for .NET --C#">
    <link rel="icon" href="@Url.Content("~/Content/images/ORMicon(200x200).png")" type="image/x-icon">
    <title>@ViewBag.Title</title>
    @ContentHelper.RefStyle("~/Content/bootstrap/bootstrap.min.css")
    @ContentHelper.RefStyle("~/Content/css/font-awesome.min.css")
    @ContentHelper.RefStyle("~/Content/css/layout-page.css")

    @ContentHelper.RefScript("~/Content/jquery/jquery-1.11.1.min.js")
    @ContentHelper.RefScript("~/Content/bootstrap/bootstrap.min.js")

    <!-- header 必须 -->
    @ContentHelper.RefScript("~/Content/js/jquery.backstretch.min.js")
    @ContentHelper.RefScript("~/Content/js/header.js")

    @ContentHelper.RefScript("~/Content/js/back-top.js")
</head>
<body>
    <header class="header fixed clearfix navbar navbar-fixed-top">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="header-left clearfix">
                        <div class="logo smooth-scroll">
                            <a href="#banner"><img id="logo" style="width:60px;height:60px;" src="@UrlHelper.GenerateContentUrl("~/Content/images/ORMicon(200x200).png", this.Context)" alt="Chloe"></a>
                        </div>
                        <div class="site-name-and-slogan smooth-scroll">
                            <div class="site-name"><a href="#">Chloe</a></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="header-right clearfix">
                        <div class="main-navigation animated">

                            <nav class="navbar navbar-default" role="navigation">
                                <div class="container-fluid">
                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                    </div>
                                    <div class="collapse navbar-collapse  scrollspy smooth-scroll" id="navbar-collapse-1">
                                        <ul class="nav navbar-nav navbar-right">
                                            <li class="active"><a ref-id="home" href="@this.Url.Action("Index","Home")">Home</a></li>
                                            <li><a ref-id="documentation" href="@this.Url.Content("~/Wiki/Document")">Documentation</a></li>
                                            <li><a ref-id="upgrade-notes" href="@this.Url.Action("UpgradeNotes", "Home", new { id = "3325175022200291328" })">Upgrade notes</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    @RenderBody()
    <footer>
        <div style="text-align:center;">
            <p style="margin:0;color: #828282">
                QQ群：<span>325936847 只要您<strong>愿意</strong>即可加入</span><br />
                博客：<a href="http://www.cnblogs.com/so9527" target="_blank">http://www.cnblogs.com/so9527</a><br />
                GitHub：<a href="https://github.com/shuxinqin/Chloe" target="_blank">https://github.com/shuxinqin/Chloe</a><br />
            </p>
            <p class="copyright-text">
                Copyright &copy; 2016 Chloe.ORM
            </p>
        </div>
    </footer>
    @RenderSection("ScriptAndStyle", required: false)
</body>
</html>